# Run CI checks for frontend code
name: Frontend CI

on: ["push", "pull_request"]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build --emptyOutDir