# Publish to PyPi package index

name: PIP Publish

on:
  release:
    types: [published]

jobs:

  publish:
    name: Publish to PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Python Dependencies
        run: |
          pip install --upgrade wheel setuptools twine
      - name: Build Binary
        run: |
          python3 setup.py sdist bdist_wheel --universal
      - name: Publish
        run: |
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY: pypi
  